#!/usr/bin/env bash
cat_r() {
	#настраиваем дефолтные значения
	curr_dir=$(pwd)
	ls_flags="-R"
	grepper=""
	output_stream="/dev/stdout"
	cache="n"
	while getopts "d:g:w:ach" FLAG; do
		case $FLAG in
			"d") 
				if [[ $OPTARG == "." ]]; then
					curr_dir=$(pwd)
				else
					curr_dir=$OPTARG
				fi
				echo -e "Ищу в \e[32;49m$curr_dir\e[0m."
				;;
			"g")
				echo -e "Буду искать \e[35;49m$OPTARG\e[0m."
				grepper=$OPTARG
				;;
			"w")
				echo "Путь $OPTARG: абсолютный (absolute) или относительный (relative)? [_a_bsolute/_r_elative]"
				read ans
				case $ans in
					"a")
						output_stream=$OPTARG
						;;
					"r")
						output_stream="$(pwd)/$OPTARG"
						;;
					*)
						echo "чё"
						exit 127
						;;
				esac
				;;
			"a")
				echo -e "Включаю \e[31;49mскрытые директории\e[0m в поиск."
				ls_flags="$ls_flags -a"
				;;
			"c")
				echo -e "Включаю \e[33;49;3mкэширование\e[0m вывода."
				cache="y"
				;;
			"h")
				echo -e "\e[30;47mcat_r\e[0m -d <ДИРЕКТОРИЯ> -g <ЧТО_ИСКАТЬ> -w <КУДА_ЗАПИСАТЬ> -a"
				echo -e "\t- Выписывает всё содержимое текстовых файлов из <ДИРЕКТОРИЯ> и поддиректорий (по дефолту: pwd)"
				echo -e "\t- Ищет <ЧТО_ИСКАТЬ> (по дефолту: ничего)"
				echo -e "\t- Выписывает \"находки\" в <КУДА_ЗАПИСАТЬ> (по дефолту: /dev/stdout)"
				echo -e "\t- Может искать в скрытых директориях через -a (по дефолту: не ищет)"

				exit 0
				;;
		esac
	done
	if [[ $output_stream != "/dev/stdout" && -f $output_stream ]]; then
		echo "$output_stream существует! Удалить? Иначе результат поиска будет ДОБАВЛЕН в конце файла. [y/n]"
		read opt
		case $opt in
			"y")
				rm $output_stream
				touch $output_stream
				;;
			"n")
				echo "Оставляем $output_stream"
				;;
			*)
				echo "не ругайся"
				exit 127
				;;
		esac
	fi

	if [[ ! -f $output_stream ]]; then
		touch $output_stream
	fi

	case $cache in
		"y")
			c_iter "$curr_dir" "$ls_flags" "$grepper" "$output_stream"
			;;
		"n")
			nc_iter "$curr_dir" "$ls_flags" "$grepper" "$output_stream"
			;;
	esac

	notify-send -a "cat_r" "закончил!"
	echo -en "\a"
	if [[ $output_stream != "/dev/stdout" ]]; then
		less $output_stream
	fi
}

# последовательно: директория, флаги ЛС, что ищем, куда выводим
nc_iter() {
	local curr_dir=$1
	local ls_flags=$2
	local grepper=$3
	local output_stream=$4
	for line in $(ls $ls_flags $curr_dir); do
		if [[ $line == *":" ]]; then
			# ЧТО
			dir_path="${line//:/}"
			if [[ -d $dir_path ]]; then
				cd $dir_path
				for file in $(ls $dir_path); do
					# придумано во сне
					if [[ (-f $file && ( $(file $file) == *"ASCII"* || $(file $file) == *"UTF-"* )) && $(realpath $file) != $output_stream ]]; then
						if [[ $grepper == "" ]]; then

							if [[ $output_stream == "/dev/stdout" ]]; then
								echo -e "\n\e[0;33m-----$(realpath $file)-----\e[0m\n"
							else
								echo -e "\n-----$(realpath $file)-----\n" >> "$output_stream"
							fi
							cat "$file" >> "$output_stream"

						else
							grep_out=$(grep -n -E "$grepper" "$file")

							if [[ $grep_out != "" ]]; then
								if [[ $output_stream == "/dev/stdout" ]]; then
									echo -e "\n\e[0;33m-----$(realpath $file)-----\e[0m\n"
								else
									echo -e "\n-----$(realpath $file)-----\n" >> "$output_stream"
								fi
								echo "$grep_out" >> "$output_stream"

							fi
						fi
					fi
				done
			fi
		fi
	done
}

#арги схожи с nc_iter
c_iter() {
	local curr_dir=$1
	local ls_flags=$2
	local grepper=$3
	local where_to_write=$4
	local cache_file="$(pwd)/cachefile"
	local output_stream=$cache_file
	if [[ -f "$cache_file" ]]; then echo "Кэш существует, считываю его..."; else
	touch "$cache_file"
	for line in $(ls $ls_flags $curr_dir); do
		if [[ $line == *":" ]]; then
			# ЧТО
			dir_path="${line//:/}"
			if [[ -d $dir_path ]]; then
				cd $dir_path
				for file in $(ls $dir_path); do
					# придумано во сне (в этот раз grepper не юзаем для отсекания, cache_file содержит ВСЁ содержимое текстовых файлов)
					if [[ (-f $file && ( $(file $file) == *"ASCII"* || $(file $file) == *"UTF-"* )) && $(realpath $file) != $output_stream ]]; then
						echo -e "\n-----$(realpath $file)-----" >> "$output_stream"
#						PREV_IFS=$IFS
#						IFS=$'\n'
#						for line in $(cat -n "$file"); do
#							echo "[$(realpath $file)]: ${line//\ /}" >> "$output_stream"
#						done
#						IFS=$PREV_IFS
						cat "$file" >> "$output_stream"
					fi
				done
			fi
		fi
	done
	fi
	# после создания кэш-файла начинаем перебирать его
	PREV_IFS=$IFS
	IFS=$'\n'
	echo "les go"
	local RESULT=""
	for line in $(cat "$cache_file"); do
		if [[ "$line" == "-----"* ]]; then
			#echo "$line" >> "$where_to_write"
			RESULT="$RESULT\n[${line//-/}]:"
		fi
		if [[ "$line" == *"$grepper"* ]]; then
			RESULT="$RESULT $line"
			#echo "$line" >> "$where_to_write"
		fi
	done
	RET=$(echo -e "$RESULT" | grep '^\[.*]: .')
	echo -e "$RET" >> "$where_to_write" 
	echo "Считывал с кэша..."
	IFS=$PREV_IFS
}
cat_r $@
